[AIDAPP - 154]: Improve error message text for issues experienced by customers
canyongbs/aidingapp pull request #146
Opened 2024-06-24 12:25 UTC by jayushi-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/AIDAPP-

### Technical Description

> Change 500 error message and image

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/aidingapp/blob/main/README.md#contributing).

2024-06-24 12:44 UTC, Orrison requested changes
One question.

Also, please take a look at the PR title and description changes above.

2024-06-24 12:44 UTC, Orrison commented on resources/svg/flowbite-500-old.svg
Is there a particular reason to keep this old file around? If not, I think it's okay to remove it.

2024-06-24 13:41 UTC, jayushi-canyon commented on resources/svg/flowbite-500-old.svg
@Orrison Deleted the file.

2024-06-24 20:17 UTC, Orrison requested changes

2024-06-24 20:17 UTC, Orrison commented on resources/svg/flowbite-500.svg
Let's rename this file to something more appropriate since it is no longer from Flowbite.

Let's do `canyongbs-500.svg`. Make sure to change the reference in the blade file once you do so.

2024-06-25 17:56 UTC, jayushi-canyon commented on resources/svg/flowbite-500.svg
@Orrison Done.

2024-06-25 22:37 UTC, Orrison approved these changes

2024-06-25 22:37 UTC, merged