[AIDAPP-237]: Introduce automatic auditing on newly created data models
canyongbs/aidingapp pull request #234
Opened 2024-09-06 17:12 UTC by kandarp-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/AIDAPP-237

### Technical Description

> Auto auditing has been implemented.

### Any deployment steps required?

> No.

### Are any Feature Flags Added?

>No.

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/aidingapp/blob/main/README.md#contributing).

2024-09-09 16:08 UTC, Orrison requested changes

2024-09-09 16:08 UTC, Orrison commented on app-modules/audit/src/Settings/AuditSettings.php
I believe the `HasDefaultSettings` interface and `defaults` method are not needed here and can be removed and deleted as we changed to a better default handling that works with the defaults of the parameter.

Try that and see if it solves the issue with the test. If not let me know and I can take a look further.

2024-09-11 12:04 UTC, kandarp-canyon commented on app-modules/audit/src/Settings/AuditSettings.php
Hi @Orrison , I've pushed the changes after removing the HasDefaultSettings interface and defaults method, but the test error is still there. can you please check?

2024-09-16 17:24 UTC, kandarp-canyon commented on app-modules/audit/src/Settings/AuditSettings.php
@Orrison Please check and provide your valuable feedback.

2024-09-18 17:22 UTC, Orrison requested changes

2024-09-18 17:22 UTC, Orrison commented on app-modules/audit/tests/AuditListenerTest.php
> +    $auditSettings->audited_models_exclude[] = [];
This should be resetting it to a blank array, not setting a new value as a blank array

```suggestion
    $auditSettings->audited_models_exclude = [];
```

2024-09-18 19:29 UTC, Orrison approved these changes

2024-09-18 19:37 UTC, merged