[AIDAPP-333]: Introduce the Assignment Type Individual so that all new service requests are assigned to a specific manager.
canyongbs/aidingapp pull request #315
Opened 2024-11-08 11:56 UTC by payal-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/AIDAPP-333

### Technical Description

> Introduce the Assignment Type Individual so that all new service requests are assigned to a specific manager.

### Any deployment steps required?

> No

### Are any Feature Flags and/or Data Migrations that can eventually be removed Added?

> No
_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/aidingapp/blob/main/README.md#contributing).

2024-11-09 02:13 UTC, Orrison submitted a review, later dismissed

2024-11-09 02:13 UTC, Orrison commented on app-modules/service-management/src/Observers/ServiceRequestObserver.php
> +                    'assigned_by_id' => auth()->user()?->id ?? null,
Let's make sure to use `getKey()` here and I don't think you need the null coalescing as the `?` on `user()` should return `null` if there is no user

2024-11-13 14:13 UTC, danharrin requested changes

2024-11-13 14:13 UTC, danharrin commented on app-modules/service-management/src/Observers/ServiceRequestObserver.php
> +                        'assigned_by_id' => auth()->user()?->getKey(),
```suggestion
                        'assigned_by_id' => $user->getKey(),
```

2024-11-13 14:33 UTC, danharrin requested changes

2024-11-13 14:33 UTC, danharrin commented on app-modules/service-management/src/Observers/ServiceRequestObserver.php
> +                        'assigned_by_id' => $user()->getKey(),
```suggestion
                        'assigned_by_id' => $user->getKey(),
```

2024-11-13 14:53 UTC, danharrin approved these changes

2024-11-13 15:01 UTC, merged