[AIDAPP-370]: Restrict the ability to grant overly permissive rights to users.
canyongbs/aidingapp pull request #337
Opened 2024-12-02 16:10 UTC by kandarp-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/AIDAPP-370

### Technical Description

> Restrict the ability to grant overly permissive rights to users.

### Any deployment steps required?

> No.

### Are any Feature Flags and/or Data Migrations that can eventually be removed Added?

> No.

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/aidingapp/blob/main/README.md#contributing).

2024-12-03 23:11 UTC, Orrison requested changes

2024-12-04 18:16 UTC, kandarp-canyon commented on app-modules/authorization/src/Models/Role.php
> +            ->where('name', Authenticatable::SUPER_ADMIN_ROLE)
Done

2024-12-04 18:17 UTC, kandarp-canyon commented on app-modules/authorization/database/migrations/2024_12_02_151546_data_change_authorization.super_admin_to_sass_global_admin_in_roles_table.php
Added feature flag.

2024-12-04 18:17 UTC, kandarp-canyon commented on app-modules/authorization/tests/Feature/Filament/Resources/User/EditUserTest.php
> +it('Not allows user which has not SaaS Global Admin role to assign SaaS Global Admin role to other user', function () {
updated

2024-12-04 18:17 UTC, kandarp-canyon commented on app-modules/contact/src/Filament/Resources/ContactResource/RelationManagers/ServiceRequestsRelationManager.php
> +                $query->when(! auth()->user()->hasRole(Authenticatable::SUPER_ADMIN_ROLE), function (Builder $q) {
Added.

2024-12-04 18:17 UTC, kandarp-canyon commented on app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/CreateServiceRequest.php
> +                            ->options(ServiceRequestType::when(! auth()->user()->hasRole(Authenticatable::SUPER_ADMIN_ROLE), function (Builder $query) {
Added.

2024-12-04 18:17 UTC, kandarp-canyon commented on app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/EditServiceRequest.php
> +                                            ->when(! auth()->user()->hasRole(Authenticatable::SUPER_ADMIN_ROLE), function (Builder $query) {
Added.

2024-12-04 18:17 UTC, kandarp-canyon commented on app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
> +                ->when(! auth()->user()->hasRole(Authenticatable::SUPER_ADMIN_ROLE), function (Builder $q) {
Added.

2024-12-04 18:17 UTC, kandarp-canyon commented on app-modules/service-management/src/Filament/Resources/ServiceRequestResource/Pages/ListServiceRequests.php
> +                                ->when(! auth()->user()->hasRole(Authenticatable::SUPER_ADMIN_ROLE), function (Builder $query) {
Added.

2024-12-04 18:17 UTC, kandarp-canyon commented on app-modules/service-management/src/Policies/ServiceRequestPolicy.php
> +        if (! auth()->user()->hasRole(Authenticatable::SUPER_ADMIN_ROLE)) {
Added.

2024-12-04 18:18 UTC, kandarp-canyon commented on app-modules/service-management/src/Policies/ServiceRequestPolicy.php
> +        if (! auth()->user()->hasRole(Authenticatable::SUPER_ADMIN_ROLE)) {
Added.

2024-12-04 18:18 UTC, kandarp-canyon commented on app-modules/service-management/src/Policies/ServiceRequestPolicy.php
> +        if (! auth()->user()->hasRole(Authenticatable::SUPER_ADMIN_ROLE)) {
Added.

2024-12-04 18:18 UTC, kandarp-canyon commented on app-modules/service-management/src/Policies/ServiceRequestPolicy.php
> +        if (! auth()->user()->hasRole(Authenticatable::SUPER_ADMIN_ROLE)) {
Added.

2024-12-04 18:18 UTC, kandarp-canyon commented on app-modules/service-management/src/Policies/ServiceRequestPolicy.php
> +        if (! auth()->user()->hasRole(Authenticatable::SUPER_ADMIN_ROLE)) {
Added.

2024-12-04 18:18 UTC, kandarp-canyon commented on app-modules/service-management/src/Policies/ServiceRequestPolicy.php
> +        if (! auth()->user()->hasRole(Authenticatable::SUPER_ADMIN_ROLE)) {
Added.

2024-12-04 18:18 UTC, kandarp-canyon commented on app/Jobs/CreateTenantUser.php
> +            $user->roles()->sync(Role::where('name', Authenticatable::SUPER_ADMIN_ROLE)->firstOrFail());
Added.

2024-12-04 18:18 UTC, kandarp-canyon commented on app/Providers/AuthServiceProvider.php
> +            return $authenticatable->hasRole(Authenticatable::SUPER_ADMIN_ROLE) && ! $result instanceof FeatureAccessResponse
Added.

2024-12-04 18:18 UTC, kandarp-canyon commented on database/seeders/SampleSuperAdminUserSeeder.php
> +            $superAdminRole = Role::where('name', Authenticatable::SUPER_ADMIN_ROLE)->firstOrFail();
Added.

2024-12-04 18:18 UTC, kandarp-canyon commented on app-modules/authorization/tests/Feature/Filament/Resources/User/EditUserTest.php
> +            return empty($options) ? true : false;
Updated

2024-12-04 18:19 UTC, kandarp-canyon commented on app-modules/authorization/tests/Feature/Filament/Resources/User/EditUserTest.php
> +        })->assertSuccessful();
Removed.

2024-12-04 19:36 UTC, merged