[AIDAPP-394]: Create email templates in the service request types that govern the emails that are sent out for a customer
canyongbs/aidingapp pull request #375
Opened 2024-12-31 17:37 UTC by amit-canyon

### Ticket(s) or GitHub Issue

- https://canyongbs.atlassian.net/browse/AIDAPP-394

### Technical Description

> Create email templates in the service request types that govern the emails that are sent out for a customer

### Any deployment steps required?

> No

### Are any Feature Flags and/or Data Migrations that can eventually be removed Added?

> No

_______________________________________________

#### Before contributing and submitting this PR, make sure you have Read, agree, and are compliant with the [contributing guidelines](https://github.com/canyongbs/aidingapp/blob/main/README.md#contributing).

2025-01-07 11:53 UTC, danharrin requested changes

2025-01-07 11:53 UTC, danharrin commented on app-modules/service-management/database/migrations/2024_12_30_090123_create_service_request_type_email_templates_table.php
> +            $table->enum('type', ['created', 'assigned', 'update', 'status-change', 'closed', 'survey-response'])->default('created');
Unless Kevin told you to use an enum column and I missed the memo, please remove this and replace it with a string

2025-01-07 11:53 UTC, danharrin commented on app-modules/service-management/database/factories/ServiceRequestTypeEmailTemplateFactory.php
> +            'body' => $this->faker->paragraph(),
I think these are JSONB columns so does this factory work?

2025-01-07 11:53 UTC, danharrin commented on app-modules/service-management/src/Enums/ServiceRequestEmailTemplateType.php
> +        return $this->value;
I think the values need translating into more human-friendly strings like `Created` and `Status change`

2025-01-07 11:53 UTC, danharrin commented on app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource.php
> +                    ->label(Str::headline($type->getLabel()))
If you move the `headline()` (as above) into the enum you won't need it here

2025-01-07 11:53 UTC, danharrin commented on app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ServiceRequestTypeEmailTemplatePage.php
> +        parent::save($shouldRedirect, $shouldSendSavedNotification);
Instead of calling `save()`, maybe just call the part of the method that sends the notification? As we don't want the service request type to be saved

2025-01-07 11:53 UTC, danharrin commented on app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ServiceRequestTypeEmailTemplatePage.php
> +        $data['service_request_type_id'] = $getRecord->id;
Can you explain why this needs to be filled here?

2025-01-07 11:53 UTC, danharrin commented on app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ServiceRequestTypeEmailTemplatePage.php
> +        $this->callHook('afterFill');
```suggestion
        $this->form->fill($data);
```

2025-01-08 12:13 UTC, danharrin submitted a review, later dismissed

2025-01-08 12:13 UTC, danharrin commented on app-modules/service-management/src/Enums/ServiceRequestEmailTemplateType.php
> +        return $this->value;
Sorry, I meant doing the translation in this getLabel() function, the values should still be `created`, `status_change` etc

2025-01-08 12:13 UTC, danharrin commented on app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ServiceRequestTypeEmailTemplatePage.php
> +        $this->form->fill($data);
```suggestion
        $this->form->fill($this->template?->only(['subject', 'body']));
```

2025-01-08 12:13 UTC, danharrin commented on app-modules/service-management/src/Filament/Resources/ServiceRequestTypeResource/Pages/ServiceRequestTypeEmailTemplatePage.php
> +        unset($this->template);
```suggestion
        $data = $this->form->getState();

        if ($this->template) {
            $this->template->update($data);
        } else {
            $data['service_request_type_id'] = $this->getRecord()->id;
            $data['type'] = $this->type;
            
            $this->getRecord()?->templates()->create($data);

            unset($this->template);
        }
```

2025-01-08 23:27 UTC, Orrison requested changes

2025-01-08 23:36 UTC, Orrison approved these changes

2025-01-08 23:43 UTC, merged